# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-17 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='popularity',
            field=models.DecimalField(decimal_places=2, default='0,00', max_digits=5),
        ),
    ]
