# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190503_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='details',
        ),
    ]
