# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-17 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190317_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='confirmation_code',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Gender'),
        ),
    ]
