# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_useraccount_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='confirmation_code',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='confirmation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
