# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-17 22:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190317_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_from', to=settings.AUTH_USER_MODEL)),
                ('user_account_blocked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('user_account_given', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_given', to=settings.AUTH_USER_MODEL)),
                ('user_account_received', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
