# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_blockuser_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userphoto',
            options={'verbose_name': 'User photo', 'verbose_name_plural': 'Users photos'},
        ),
        migrations.AddField(
            model_name='userphoto',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
