# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190426_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='confirmation_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
