# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 20:15
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190501_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='popularity',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=5),
        ),
    ]
